version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: laravel-mix
    versions:
    - 6.0.11
    - 6.0.13
    - 6.0.16
  - dependency-name: bootstrap-sass
    versions:
    - 3.4.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: jquery
    versions:
    - 3.5.1
